name: validation
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  dto:
    git:
      url: https://github.com/kazky-dytynstva/dto
      ref: 1.4.16
